title = "cPanel's Favorite Recipes"
baseURL = "https://ng-vincent.github.io/cPanel-Assessment"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
copyright = "Vincent Nguyen"

DefaultContentLanguage = "en"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true
summaryLength = 24

[menu]
[[menu.main]]
  name = "Recipes"
  url = "/recipes/"
  weight = 1
[[menu.main]]
  name = "Feed"
  url = "/feed/"
  weight = 100

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "github"
url = "https://github.com/NG-Vincent/cPanel-Assessment"
